/**
 * Reads an acceptance answer sheet generated by run-acceptance.ts and emits
 * a filtered version containing ONLY questions with non-high confidence
 * (partial or degraded). High-confidence answers are dropped — the user trusts
 * those by default.
 *
 * Run: npx tsx scripts/filter-acceptance-answers.ts <input.md>
 */
import * as fs from 'node:fs';
import * as path from 'node:path';

function main() {
	const inputArg = process.argv[2];
	if (!inputArg) {
		console.error('Usage: tsx scripts/filter-acceptance-answers.ts <input.md>');
		process.exit(1);
	}
	const inputPath = path.resolve(inputArg);
	const raw = fs.readFileSync(inputPath, 'utf8');

	// The doc starts with a header block, then `---` separators between
	// question blocks. Each block contains exactly one `**Confidence:** ...`
	// line. We keep blocks where the confidence is NOT 🟢 / 'high'.
	const headerEnd = raw.indexOf('\n---\n');
	const header = headerEnd > -1 ? raw.slice(0, headerEnd) : raw;
	const body = headerEnd > -1 ? raw.slice(headerEnd + 5) : '';

	// Split on each `### ` (question header). Keep the leading text before the
	// first heading (likely a section heading like `## Section ...`).
	const parts = body.split(/(?=^### )/m);

	const kept: string[] = [];
	let totalQuestions = 0;
	let highCount = 0;
	let partialCount = 0;
	let degradedCount = 0;
	let unmarkedCount = 0;
	let currentSection = '';

	for (const part of parts) {
		// Pre-question chunk (section headings, etc.) — pass through but track
		// the most recent section so kept questions still appear under their
		// section header.
		const sectionMatch = part.match(/^(##\s.+?)$/m);
		if (sectionMatch) {
			currentSection = sectionMatch[1];
		}
		const isQuestionBlock = /^### /m.test(part);
		if (!isQuestionBlock) {
			// Don't emit lone section headers — we attach them per-kept-block
			continue;
		}
		totalQuestions++;
		const conf = part.match(/^\*\*Confidence:\*\*\s+(🟢|🟡|🔴)\s+(\w+)/m);
		if (!conf) {
			unmarkedCount++;
			// No confidence line — be safe and keep it
			kept.push(currentSection ? `\n${currentSection}\n\n${part}` : part);
			continue;
		}
		const level = conf[2];
		if (level === 'high') {
			highCount++;
			continue;
		}
		if (level === 'partial') partialCount++;
		else if (level === 'degraded') degradedCount++;
		kept.push(currentSection ? `\n${currentSection}\n\n${part}` : part);
	}

	// Deduplicate adjacent section headers (a section may have multiple kept
	// questions; we only need to print the header once).
	const deduped: string[] = [];
	let lastSectionPrinted = '';
	for (const block of kept) {
		const m = block.match(/^\n(## .+?)\n/);
		if (m) {
			const section = m[1];
			if (section === lastSectionPrinted) {
				deduped.push(block.replace(/^\n## .+?\n\n/, ''));
			} else {
				deduped.push(block);
				lastSectionPrinted = section;
			}
		} else {
			deduped.push(block);
		}
	}

	const stamp = path.basename(inputPath, '.md').replace(/^ask-bims-acceptance-answers-/, '');
	const outputPath = inputPath.replace(/\.md$/, '-non-high-confidence.md');

	const out: string[] = [];
	out.push(`# Ask BIMS — Non-High-Confidence Answers Only (filtered from ${stamp})`);
	out.push('');
	out.push(`Source: \`${path.basename(inputPath)}\``);
	out.push('');
	out.push(`Filter rule: kept any answer with confidence 🟡 partial or 🔴 degraded; dropped 🟢 high. The dropped answers are presumed correct by the user (the agent's tool results showed no integrity issues or truncation).`);
	out.push('');
	out.push(`**Breakdown of the ${totalQuestions}-question run:**`);
	out.push(`- 🟢 high (dropped): ${highCount}`);
	out.push(`- 🟡 partial (kept): ${partialCount}`);
	out.push(`- 🔴 degraded (kept): ${degradedCount}`);
	if (unmarkedCount > 0) out.push(`- ⚪ no confidence line (kept defensively): ${unmarkedCount}`);
	out.push('');
	out.push(`**What "non-high confidence" means here:** the tool that answered the question either surfaced a dataIntegrityNote (a documented known gap, like empty reagentChain), or returned a not-found / truncated result, or errored. The answer text may still be perfectly correct — the badge just flags that the underlying data condition wasn't fully clean.`);
	out.push('');
	out.push('---');
	out.push('');
	out.push(deduped.join(''));

	fs.writeFileSync(outputPath, out.join('\n'), 'utf8');
	console.log(`✓ Wrote ${outputPath}`);
	console.log(`  Kept ${partialCount + degradedCount + unmarkedCount} of ${totalQuestions} questions`);
}

main();
